version: '3.8'

services:
  app:
    container_name: whatsapp-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    # depends_on:
    #   - redis
    networks:
      - app-network
    volumes:
      - app-logs:/app/logs

  # redis:
  #   container_name: whatsapp-redis
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   restart: unless-stopped
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  # redis-data:
  app-logs: